### ISSUE TITLE
205-while-loop-solution 

### ISSUE THREAD

**Issue by dennisnpc** [UniversityOfPlymouthComputing/SoftwareEngineering#5]
205-while-loop-solution sets i = -10 at the beginning instead of i = 10

![imgpsh_mobile_save](https://github.com/UniversityOfPlymouthComputing/SoftwareEngineering/assets/146251437/f3b1c6aa-2a6e-4454-a017-74b2b47961a0)

**Comment by noutram-old-uopaccount** [comment]
Well spotted! I've now fixed it. Thank you for raising this, it really helps.
